config/routes.rb
Rails.application.routes.draw do
  root 'liquid_templates#index'
  resources :liquid_templates
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/liquid_template.rb
class LiquidTemplate < ApplicationRecord
  validates :content, presence: true
  validate :syntax_errors

  private
  def syntax_errors
    Liquid::Template.parse(self.content)
  rescue Liquid::SyntaxError => e
    errors.add(:content, e.message)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/liquid_templates_controller.rb
class LiquidTemplatesController < ApplicationController
  before_action :set_liquid_template, only: [:show, :edit, :update, :destroy]

  # GET /liquid_templates
  # GET /liquid_templates.json
  def index
    @liquid_templates = LiquidTemplate.all
  end

  # GET /liquid_templates/1
  # GET /liquid_templates/1.json
  def show
  end

  # GET /liquid_templates/new
  def new
    @liquid_template = LiquidTemplate.new
  end

  # GET /liquid_templates/1/edit
  def edit
  end

  # POST /liquid_templates
  # POST /liquid_templates.json
  def create
    @liquid_template = LiquidTemplate.new(liquid_template_params)

    respond_to do |format|
      if @liquid_template.save
        format.html { redirect_to @liquid_template, notice: 'Liquid template was successfully created.' }
        format.json { render :show, status: :created, location: @liquid_template }
      else
        format.html { render :new }
        format.json { render json: @liquid_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /liquid_templates/1
  # PATCH/PUT /liquid_templates/1.json
  def update
    respond_to do |format|
      if @liquid_template.update(liquid_template_params)
        format.html { redirect_to @liquid_template, notice: 'Liquid template was successfully updated.' }
        format.json { render :show, status: :ok, location: @liquid_template }
      else
        format.html { render :edit }
        format.json { render json: @liquid_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /liquid_templates/1
  # DELETE /liquid_templates/1.json
  def destroy
    @liquid_template.destroy
    respond_to do |format|
      format.html { redirect_to liquid_templates_url, notice: 'Liquid template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_liquid_template
      @liquid_template = LiquidTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def liquid_template_params
      params.require(:liquid_template).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/liquid_templates_helper.rb
module LiquidTemplatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiquidTemplateValidation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/liquid_templates/_form.html.haml
= form_for @liquid_template do |f|
  - if @liquid_template.errors.any?
    #error_explanation
      %h2= "#{pluralize(@liquid_template.errors.count, "error")} prohibited this liquid_template from being saved:"
      %ul
        - @liquid_template.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/liquid_templates/edit.html.haml
%h1 Editing liquid_template

= render 'form'

= link_to 'Show', @liquid_template
\|
= link_to 'Back', liquid_templates_path

app/views/liquid_templates/index.html.haml
%h1 Listing liquid_templates

%table
  %thead
    %tr
      %th Content
      %th
      %th
      %th

  %tbody
    - @liquid_templates.each do |liquid_template|
      %tr
        %td= liquid_template.content
        %td= link_to 'Show', liquid_template
        %td= link_to 'Edit', edit_liquid_template_path(liquid_template)
        %td= link_to 'Destroy', liquid_template, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Liquid template', new_liquid_template_path

app/views/liquid_templates/new.html.haml
%h1 New liquid_template

= render 'form'

= link_to 'Back', liquid_templates_path

app/views/liquid_templates/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @liquid_template.content

= link_to 'Edit', edit_liquid_template_path(@liquid_template)
\|
= link_to 'Back', liquid_templates_path